# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 04:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('magic', '0001_initial'), ('magic', '0002_auto_20170927_0037'), ('magic', '0003_card'), ('magic', '0004_auto_20170927_0108'), ('magic', '0005_auto_20170927_0112'), ('magic', '0006_auto_20170928_2238'), ('magic', '0007_auto_20170928_2258'), ('magic', '0008_card_card_type'), ('magic', '0009_auto_20170929_0100'), ('magic', '0010_auto_20170929_0109'), ('magic', '0011_auto_20170929_0142')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='code')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('gatherer_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='gatherer code')),
                ('old_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='old_code')),
                ('magic_cards_info_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='magic cards info code')),
                ('release_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='release date')),
                ('border', models.CharField(blank=True, max_length=255, null=True, verbose_name='barder')),
                ('set_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='type')),
                ('block', models.CharField(blank=True, max_length=255, null=True, verbose_name='block')),
                ('online_only', models.CharField(blank=True, max_length=255, null=True, verbose_name='online only')),
                ('booster', models.CharField(blank=True, max_length=255, null=True, verbose_name='booster')),
                ('mkm_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='mkm_id')),
                ('mkm_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='mkm_name')),
                ('last_updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='last updated at')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('multiverse_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='multiverse id')),
                ('layout', models.CharField(blank=True, max_length=255, null=True, verbose_name='layout')),
                ('names', models.CharField(blank=True, max_length=255, null=True, verbose_name='names')),
                ('mana_cost', models.CharField(blank=True, max_length=255, null=True, verbose_name='mana cost')),
                ('cmc', models.IntegerField(blank=True, null=True, verbose_name='converted mana cost')),
                ('color_identity', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('card_supertypes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('card_subtypes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('rarity', models.CharField(blank=True, max_length=255, null=True, verbose_name='rarity')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='text')),
                ('flavor', models.CharField(blank=True, max_length=255, null=True, verbose_name='flavor')),
                ('artist', models.CharField(blank=True, max_length=255, null=True, verbose_name='artist')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='number')),
                ('power', models.CharField(blank=True, max_length=255, null=True, verbose_name='power')),
                ('toughness', models.CharField(blank=True, max_length=255, null=True, verbose_name='toughness')),
                ('loyalty', models.CharField(blank=True, max_length=255, null=True, verbose_name='loyalty')),
                ('variations', models.CharField(blank=True, max_length=255, null=True, verbose_name='variations')),
                ('watermark', models.CharField(blank=True, max_length=255, null=True, verbose_name='watermark')),
                ('border', models.CharField(blank=True, max_length=255, null=True, verbose_name='border')),
                ('timeshifted', models.CharField(blank=True, max_length=255, null=True, verbose_name='timeshifted')),
                ('hand', models.CharField(blank=True, max_length=255, null=True, verbose_name='hand')),
                ('life', models.CharField(blank=True, max_length=255, null=True, verbose_name='life')),
                ('reserved', models.CharField(blank=True, max_length=255, null=True, verbose_name='reserved')),
                ('release_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='release date')),
                ('starter', models.CharField(blank=True, max_length=255, null=True, verbose_name='starter')),
                ('rulings', models.CharField(blank=True, max_length=255, null=True, verbose_name='rulings')),
                ('foreign_names', models.CharField(blank=True, max_length=255, null=True, verbose_name='foreign_names')),
                ('printings', models.CharField(blank=True, max_length=255, null=True, verbose_name='printings')),
                ('original_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='original text')),
                ('original_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='original type')),
                ('legalities', models.CharField(blank=True, max_length=255, null=True, verbose_name='legalities')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='source')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='image url')),
                ('set_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='set_code')),
                ('set_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='set name')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='external id')),
                ('last_updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, max_length=255, null=True, verbose_name='last updated at')),
                ('card_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='magic.CardSet', verbose_name='set')),
                ('card_types', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('letter', models.CharField(max_length=1, verbose_name='letter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='archetype',
            name='colors',
            field=models.ManyToManyField(related_name='archetype_colors', to='magic.Color'),
        ),
        migrations.AddField(
            model_name='card',
            name='colors',
            field=models.ManyToManyField(related_name='card_colors', to='magic.Color', verbose_name='colors'),
        ),
        migrations.AlterField(
            model_name='card',
            name='foreign_names',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.IntegerField(blank=True, null=True, verbose_name='power'),
        ),
        migrations.AlterField(
            model_name='card',
            name='printings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='toughness',
            field=models.IntegerField(blank=True, null=True, verbose_name='toughness'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='card_type'),
        ),
        migrations.AlterField(
            model_name='card',
            name='original_text',
            field=models.TextField(blank=True, null=True, verbose_name='original text'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rulings',
            field=models.TextField(blank=True, null=True, verbose_name='rulings'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.URLField(blank=True, max_length=1023, null=True, verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='card',
            name='legalities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='legalities'),
        ),
    ]
