# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='last updated at'),
        ),
    ]
