# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0002_auto_20170927_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('multiverse_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('layout', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('names', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('mana_cost', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('cmc', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('colors', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('color_identity', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('card_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('card_supertypes', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('card_subtypes', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('rarity', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('flavor', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('artist', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('power', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('toughness', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('loyalty', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('variations', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('watermark', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('border', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('timeshifted', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('hand', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('life', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('reserved', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('release_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('starter', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('rulings', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('foreign_names', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('printings', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('original_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('original_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('legalities', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('set_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('set_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='zzzzzzzzzz')),
                ('last_updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, max_length=255, null=True, verbose_name='last updated at')),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='magic.CardSet', verbose_name='set')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
