# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0003_auto_20170929_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flavor',
            field=models.TextField(blank=True, null=True, verbose_name='flavor'),
        ),
    ]
