# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0003_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='magic.CardSet', verbose_name='set'),
        ),
    ]
