# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0004_auto_20170927_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='artist'),
        ),
        migrations.AlterField(
            model_name='card',
            name='border',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='border'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_subtypes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subtypes'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_supertypes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='supertypes'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cmc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='converted mana cost'),
        ),
        migrations.AlterField(
            model_name='card',
            name='color_identity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='color identity'),
        ),
        migrations.AlterField(
            model_name='card',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='colors'),
        ),
        migrations.AlterField(
            model_name='card',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='external id'),
        ),
        migrations.AlterField(
            model_name='card',
            name='flavor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='flavor'),
        ),
        migrations.AlterField(
            model_name='card',
            name='foreign_names',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='foreign_names'),
        ),
        migrations.AlterField(
            model_name='card',
            name='hand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='hand'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='card',
            name='layout',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='layout'),
        ),
        migrations.AlterField(
            model_name='card',
            name='legalities',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='legalities'),
        ),
        migrations.AlterField(
            model_name='card',
            name='life',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='life'),
        ),
        migrations.AlterField(
            model_name='card',
            name='loyalty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='loyalty'),
        ),
        migrations.AlterField(
            model_name='card',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='mana cost'),
        ),
        migrations.AlterField(
            model_name='card',
            name='multiverse_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='multiverse id'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='card',
            name='names',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='names'),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='card',
            name='original_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='original text'),
        ),
        migrations.AlterField(
            model_name='card',
            name='original_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='original type'),
        ),
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='power'),
        ),
        migrations.AlterField(
            model_name='card',
            name='printings',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='printings'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='rarity'),
        ),
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='release date'),
        ),
        migrations.AlterField(
            model_name='card',
            name='reserved',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='reserved'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rulings',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='rulings'),
        ),
        migrations.AlterField(
            model_name='card',
            name='set_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='set_code'),
        ),
        migrations.AlterField(
            model_name='card',
            name='set_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='set name'),
        ),
        migrations.AlterField(
            model_name='card',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='card',
            name='starter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='starter'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='card',
            name='timeshifted',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='timeshifted'),
        ),
        migrations.AlterField(
            model_name='card',
            name='toughness',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='toughness'),
        ),
        migrations.AlterField(
            model_name='card',
            name='variations',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='variations'),
        ),
        migrations.AlterField(
            model_name='card',
            name='watermark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='watermark'),
        ),
    ]
