# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0004_auto_20170929_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='is_tribal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='border',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='border'),
        ),
    ]
