# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0005_auto_20170929_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardset',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterField(
            model_name='cardset',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='release date'),
        ),
    ]
