# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 01:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0006_auto_20170928_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_type',
        ),
        migrations.AddField(
            model_name='card',
            name='card_types',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='colors',
            field=models.ManyToManyField(related_name='archetype_colors', to='magic.Color'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_subtypes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_supertypes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cmc',
            field=models.IntegerField(blank=True, null=True, verbose_name='converted mana cost'),
        ),
        migrations.AlterField(
            model_name='card',
            name='color_identity',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='card',
            name='colors',
        ),
        migrations.AddField(
            model_name='card',
            name='colors',
            field=models.ManyToManyField(related_name='card_colors', to='magic.Color', verbose_name='colors'),
        ),
        migrations.AlterField(
            model_name='card',
            name='foreign_names',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.IntegerField(blank=True, null=True, verbose_name='power'),
        ),
        migrations.AlterField(
            model_name='card',
            name='printings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='toughness',
            field=models.IntegerField(blank=True, null=True, verbose_name='toughness'),
        ),
    ]
