# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0007_auto_20170928_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='card_type'),
        ),
    ]
