# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0008_card_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='original_text',
            field=models.TextField(blank=True, null=True, verbose_name='original text'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rulings',
            field=models.TextField(blank=True, null=True, verbose_name='rulings'),
        ),
    ]
