# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0009_archetype_card_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archetype',
            name='card_set',
        ),
        migrations.AddField(
            model_name='card',
            name='int_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='integer power'),
        ),
        migrations.AddField(
            model_name='card',
            name='int_toughness',
            field=models.IntegerField(blank=True, null=True, verbose_name='integer toughness'),
        ),
    ]
