# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0009_auto_20170929_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
    ]
