# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 04:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0010_auto_20170929_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.URLField(blank=True, max_length=1023, null=True, verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='card',
            name='legalities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='legalities'),
        ),
    ]
