# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 01:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0006_auto_20170928_2238'),
        ('votes', '0002_votecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchetypeVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('score', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='score')),
                ('archetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='magic.Archetype', verbose_name='archetype votes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='votecard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='votecard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='name',
        ),
        migrations.AddField(
            model_name='vote',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='magic.Card', verbose_name='user'),
        ),
        migrations.AddField(
            model_name='vote',
            name='score',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='score'),
        ),
        migrations.DeleteModel(
            name='VoteCard',
        ),
        migrations.AddField(
            model_name='archetypevote',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archetype_votes', to='votes.Vote', verbose_name='archetype vote'),
        ),
    ]
